### ISSUE TITLE
You may benefit from the `Default` trait.

### ISSUE THREAD

**Issue by P-E-P** [alexandrefresnais/gb-rs#3]
https://github.com/alexandrefresnais/gb-rs/blob/d8f0fa94fd02bb4ed8d3ecae32f26194faa37752/src/timer.rs#L33

This seems to use pre-defined values, the constructor does not seems to construct in itself here.

**Comment by alexandrefresnais** [comment]
Indeed, thank you !
Implemented in 8d035644929b22bb8d4eb645159aa94514fa187e
